window.sections = {
  home: {
    eyebrow: "Season 2026 • Preseason",
    title: "Welcome, Coach",
    action: "Start career",
    tag: "Build your legacy",
    heading: "LoL eSport Manager",
    description:
      "Zarządzaj składem, sztabem, transferami i finansami klubu. Przygotuj drużynę do lig, turniejów oraz walki o międzynarodowe trofea.",
    cards: [
      ["Next match", "Brak zaplanowanego meczu", "Dołącz do ligi lub turnieju"],
      ["Team morale", "Stabilne", "Zależy od składu i ostatnich wyników"],
      ["Budget", "€500k", "Gotowe na transfery"],
    ],
  },
  mailbox: { layout: "mailbox" },
  mailboxOld: {
    eyebrow: "Club communication",
    title: "Mailbox",
    action: "Compose reply",
    tag: "Wiadomości klubowe",
    heading: "Inbox",
    description: "Sprawdzaj wiadomości od zarządu, zawodników, sponsorów oraz organizatorów rozgrywek.",
    cards: [
      ["Board", "Cele sezonu", "Awans do play-offów i dodatni budżet"],
      ["Player", "Prośba o rozmowę", "Midlaner chce omówić plan treningowy"],
      ["League", "Terminarz", "Pierwszy mecz pojawi się po dołączeniu do ligi"],
    ],
  },
  squad: { layout: "squad" },
  staff: { layout: "staff" },
  staffOld: {
    eyebrow: "Backroom team",
    title: "Staff",
    action: "Hire staff",
    tag: "Performance team",
    heading: "Sztab",
    description: "Zarządzaj trenerami, analitykami i psychologiem, którzy pomagają drużynie rozwijać taktykę oraz mental.",
    cards: [
      ["Head coach", "Marta Kowalska", "Strategia draftu • 92"],
      ["Analyst", "Oskar Lewandowski", "VOD review • 87"],
      ["Psychologist", "Ewa Mazur", "Mental reset • 84"],
    ],
  },
  gamingHome: { layout: "gamingHouse" },
  transfer: { layout: "transfer" },
  transferOld: {
    eyebrow: "Market window",
    title: "Transfer",
    action: "Make offer",
    tag: "Open market",
    heading: "Transfery",
    description: "Negocjuj kontrakty, sprzedawaj rezerwowych i poluj na talenty, które podniosą poziom drużyny.",
    cards: [
      ["Target", "Lee \"Spark\" Min", "Mid • €640k buyout"],
      ["Offer", "Support prospect", "Kontrakt 2 lata • w trakcie"],
      ["Sale", "Academy ADC", "Zainteresowanie 3 klubów"],
    ],
  },
  scouting: { layout: "scouting" },
  scoutingOld: {
    eyebrow: "Talent network",
    title: "Scouting",
    action: "Send scout",
    tag: "Hidden gems",
    heading: "Scouting",
    description: "Wysyłaj skautów do lig regionalnych i akademii, aby znaleźć przyszłe gwiazdy zanim zrobi to konkurencja.",
    cards: [
      ["Region", "Korea Challengers", "2 raporty gotowe jutro"],
      ["Prospect", "Toplaner 17 lat", "Potencjał A-"],
      ["Scout", "Anna Wiśniewska", "Specjalizacja: mikro mechanika"],
    ],
  },
  tournaments: { layout: "tournaments" },
  tournamentsOld: {
    eyebrow: "Competition calendar",
    title: "Tournaments",
    action: "Register team",
    tag: "Upcoming events",
    heading: "Turnieje",
    description: "Wybieraj turnieje, planuj bootcampy i pilnuj, aby zawodnicy byli w szczycie formy na najważniejsze mecze.",
    cards: [
      ["Cup", "Rift Masters", "Start za 18 dni • Prize €250k"],
      ["Qualifier", "EU Invitational", "Zapisy otwarte"],
      ["Bootcamp", "Warszawa", "7 dni przed play-offami"],
    ],
  },
  leagues: { layout: "leagues" },
  leaguesOld: {
    eyebrow: "League overview",
    title: "Leagues",
    action: "View table",
    tag: "Spring split",
    heading: "Ligi",
    description: "Śledź terminarz, tabelę, formę rywali i punkty potrzebne do awansu do fazy play-off.",
    cards: [
      ["Position", "3rd place", "Bilans 6-3"],
      ["Next rival", "Dragon Forge", "Agresywny jungle pathing"],
      ["Playoffs", "72% chance", "Według aktualnej symulacji"],
    ],
  },
  finances: { layout: "finances" },
  financesOld: {
    eyebrow: "Club economy",
    title: "Finances",
    action: "Open ledger",
    tag: "Financial control",
    heading: "Finanse",
    description: "Kontroluj budżet, pensje, premie za wyniki i miesięczny przepływ gotówki klubu.",
    cards: [
      ["Balance", "€500k", "Dostępne środki"],
      ["Monthly wages", "€310k", "68% limitu płac"],
      ["Projected profit", "+€180k", "Prognoza na koniec splitu"],
    ],
  },
  sponsors: { layout: "sponsors" },
  settings: { layout: "settings" },
  sponsorsOld: {
    eyebrow: "Commercial deals",
    title: "Sponsors",
    action: "Negotiate deal",
    tag: "Partner portfolio",
    heading: "Sponsorzy",
    description: "Podpisuj umowy sponsorskie, realizuj cele marketingowe i zwiększaj prestiż organizacji.",
    cards: [
      ["Main sponsor", "HyperGear", "€900k rocznie"],
      ["Objective", "Top 4 league", "Bonus €120k"],
      ["New lead", "Energy drink brand", "Wymaga 80+ morale"],
    ],
  },
};
